apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
{{ include "..labels" . | indent 4 }}
data:
  IP4_URL: {{ .Values.ipCheck.ipv4Url | quote }}
  DO_API_BASE_URL:  {{ .Values.do.baseUrl | quote }}
  DO_DOMAIN: {{ required "You must specify a domain" .Values.do.domain | quote }}
  DO_RECORD_ID: {{ required "You must specify a record id" .Values.do.recordId | quote }}