apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
data:
  TZ: {{ .Values.timezone | quote }}
  ADVERTISE_IP: "http://{{ .Values.host }}:32400/"