apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
type: Opaque
stringData:
  PLEX_CLAIM: {{ .Values.claimToken | quote }}