image:
  repository: plexinc/pms-docker
  tag: latest
  pullPolicy: IfNotPresent

timezone: Europe/London
claimToken: ""
host: raspberrypi.local
pv: "plex-data"
db:
  size: 1Gi

ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: raspberrypi.local
      http:
        paths:
          - /