apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "..labels" . | indent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: {{ .Values.image.repository }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            {{- if .Values.proxy }}
            - name: http_proxy
              value: {{ .Values.proxy | quote }}
            - name: https_proxy
              value: {{ .Values.proxy | quote }}
            {{- end }}
            envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secret
          restartPolicy: {{ .Values.cronjob.jobRestartPolicy }}
