apiVersion: v1
kind: Secret
metadata:
  name: {{ template "..fullname" . }}
  labels:
{{ include "..labels" . | indent 4 }}
type: Opaque
stringData:
  DO_TOKEN: {{ required "You must specify a token" .Values.do.token }}