apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
{{ include "..labels" . | indent 4 }}
type: Opaque
stringData:
  DO_TOKEN: {{ required "You must specify a token" .Values.do.token | quote }}